<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.1.2</Version>
    <Authors>Vettvangur</Authors>
    <Company>Vettvangur</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Vettvangur/Ekom.Shipping</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Vettvangur/Ekom.Shipping</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>ekom;umbraco;ecommerce;shipping</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>
</Project>
