<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Ekom.Shipping.DhlLocationFinder</PackageId>
    <Version>0.1.1</Version>
    <Description>Typed DHL Location Finder Unified client for Ekom Shipping.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    <ProjectReference Include="../../Ekom.Shipping.Core/Ekom.Shipping.Core.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <None Remove="$(MSBuildThisFileDirectory)../../../README.md"/>
    <None Update="README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>
</Project>
