<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Ekom.Shipping.U18</PackageId>
    <Description>Ekom Shipping integration for Umbraco 18.</Description>
    <DefineConstants>$(DefineConstants);UMBRACO_18</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ekom.Shipping/Ekom.Shipping.csproj" />
    <PackageReference Include="Ekom.U18" Version="0.2.273" />
    <PackageReference Include="Umbraco.Cms.Core" Version="18.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Ekom.Shipping.Umbraco.Shared/EkomShippingComposer.cs" Link="EkomShippingComposer.cs" />
    <Compile Include="../Ekom.Shipping.Umbraco.Shared/EkomShippingEvents.cs" Link="EkomShippingEvents.cs" />
  </ItemGroup>
</Project>
